### ISSUE TITLE
unable to export with --insecure flag.

### ISSUE THREAD

**Issue by RamBadduri** [jonasvinther/medusa#110]
![image](https://user-images.githubusercontent.com/99279391/209207994-daa3f792-a0b2-4a28-842b-3b96d8d31a80.png)
![image](https://user-images.githubusercontent.com/99279391/209208215-c61ead15-25bd-4bf5-ab57-2d4515628e7f.png)

Tried both Kv/kv1/kv2 and secrets flag. Nothing worked out. When tried without --insecure flag  got  ": x509: certificate signed by unknown authority" error.

**Comment by jonasvinther** [comment]
Hi @RamBadduri 
I don't think that this issue is related to Medusa. The error message is written by Vault and not Medusa. I can see that you are running Vault in a Kubernetes cluster. Maybe your issue could be something like this parson have? https://github.com/hashicorp/consul-template/issues/1138
