### ISSUE TITLE
vault:latest no longer exists in Docker Hub

### ISSUE THREAD

**Issue by infamousjoeg** [jonasvinther/medusa#135]
In the `scripts` directory are Docker Compose files that use vault:latest as a base image.

Vault has been moved from open source to source available which has eliminated any further updates starting at v14.  For this reason, a `latest` tag no longer exists.  The Docker Compose files should be pinned on tag `v1.13.3` as the last surviving open source Vault tag.

**Comment by infamousjoeg** [comment]
Good to know!  I'll close my PR for 1.13.3 on the old repository.

**Comment by jonasvinther** [comment]
Fixed in #139
