### ISSUE TITLE
os exit codes

### ISSUE THREAD

**Issue by motilevy** [jonasvinther/medusa#30]
Thank you for this tool! 
I am running it as a Kubernetes job and noticed that `medusa export ...` always returns an exit code of `0`. 
I wanted to know if you're open for a pull request to make sure all errors are returned back to main.go and change main.go to:

```
	err := cmd.Execute()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
```

Or use `log.Fatal`/`log.Fatalf` where appropriate ?
let me know which approach makes sense and I'll open a PR.

**Comment by jonasvinther** [comment]
Sure, that would be great if you can help implementing this.
Thank you for your feedback and contribution!

**Comment by jonasvinther** [comment]
Thank you so much for your contribution. I have merged the your pull request. Improving the error handling was much needed. 
Please do not hesitate to create issues if you experience any errors while using Medusa.
