### ISSUE TITLE
Cannot export data from KV v1 secret engine

### ISSUE THREAD

**Issue by jb4293** [jonasvinther/medusa#41]
Running an export fails on KV v1 secret engine, because the v1 engine doesn't use the metadata path:

    docker run medusa -a https://vault:8200 -k -t $(cat .vault-token) export secret/secretthings

    Error: no keys found using path [secret/metadata/secretthings/] on Vault instance [https://vault:8200]
    no keys found using path [secret/metadata/secretthings/] on Vault instance [https://vault:8200]`

Any chance of getting KV v1 support?

**Comment by jonasvinther** [comment]
Thank you for posting this issue. We are aware that Medusa are not fully compatible with the kv1 secret engine yet. This is one of the next features we will work on. I will keep you updated.

**Comment by lujunbofan2019** [comment]
> Thank you for posting this issue. We are aware that Medusa are not fully compatible with the kv1 secret engine yet. This is one of the next features we will work on. I will keep you updated.

Looking forward to it!

**Comment by jb4293** [comment]
> Thank you for posting this issue. We are aware that Medusa are not fully compatible with the kv1 secret engine yet. This is one of the next features we will work on. I will keep you updated.

Great!  Thank you!

**Comment by jonasvinther** [comment]
I have added support for the kv1 secret engine with merge request #42 .
If you wanna use the KV1 secret engine you now need to specify this using a flag `--engine-type kv1`. It has been implemented both for importing and exporting secrets. The default engine type is kv2. See the documentation under importing data or exporting data for more information.
I have made a new release(v0.2.0) that contains these changes.
I will close this issue, but feel free to reopen if you are experiencing any issues.
