### ISSUE TITLE
Import is wrapping the keys within extra "data"

### ISSUE THREAD

**Issue by nitinjmv** [jonasvinther/medusa#53]
Hi,
May be a silly question but I couldn't find anything related this in readme so posting it here. 

here are the commands I'm using for export/import.

docker run \
    --rm \
    -v $(shell pwd):/tmp/ \
    -e VAULT_ADDR=$(VAULT_ADDR_SOURCE) \
    -e VAULT_TOKEN=$(VAULT_TOKEN_SOURCE) \
    -e VAULT_SKIP_VERIFY=true \
    jonasvinther/medusa:latest \
    export -m=kv1 myfolder --insecure --encrypt=true --public-key=/tmp/public-key.pem -o /tmp/backup.json

docker run \
	-v $(shell pwd):/tmp/ \
	--rm \
	-e VAULT_ADDR=$(VAULT_ADDR_DESTINATION) \
	-e VAULT_TOKEN=$(VAULT_TOKEN_DESTINATION) \
	-e VAULT_SKIP_VERIFY=true \
	jonasvinther/medusa:latest \
	import -m=kv1 myfolder --insecure --decrypt=true --private-key=/tmp/private-key.pem /tmp/backup.json

For example this the export via medusa
--------------------------------------------------

project:
  myapp:
    data:
      foo2:
        data:
          foo: bar
          pizza: cheese
        options:
          cas: 0
    dummy:
      foo: bar
    kv:
      mysecret:
        foo: bar
    mysecret:
      data:
        mykey1: myjmv
        name: nitin

But this what being imported via medusa with extra "data" tag.
--------------------------------------------------------------
project:
  myapp:
    data:
      foo2:
        data:
          data:
            foo: bar
            pizza: cheese
        options:
          data:
            cas: 0
    dummy:
      data:
        foo: bar
    kv:
      mysecret:
        data:
          foo: bar
    mysecret:
      data:
        data:
          mykey1: myjmv
          name: nitin

**Comment by hokugawa** [comment]
I faced the same problem.
Looks like medusa wrote secret as kv2 format.

the original secret is like this:
```
vault read secret/example
Key                 Value
---                 -----
refresh_interval    768h
value               eyJ4(snip...)
```
but, after import, it is like this:
```
vault read secret/example
Key                 Value
---                 -----
refresh_interval    768h
data                map[value:eyJ4(snip...)]
```

using docker image `jonasvinther/medusa:0.2.2`

**Comment by nitinjmv** [comment]
Hi @hokugawa 
wondering if you have found any work around?

**Comment by hokugawa** [comment]
> wondering if you have found any work around?

I haven't, unfortunately.

**Comment by jonasvinther** [comment]
Hi @nitinjmv and @hokugawa 
Thanks for reporting this issue.
I have looked into it and found a bug in the kv1 export part. I have created a new release(https://github.com/jonasvinther/medusa/releases/tag/v0.2.3) that I hope have solved the issue. Can you please give it a try and report back to me? Thanks!

**Comment by hokugawa** [comment]
@jonasvinther 
Awesome, I've confirmed that it's solved by v0.2.3.
Thanks!!

**Comment by nitinjmv** [comment]
Thanks @jonasvinther 
I confirm too..working as expected.

**Comment by kayahk** [comment]
@jonasvinther I think the bug has returned, just tried out the current version 0.50.0 on darwin/arm64 and the data prefix path is there, regardless of the `--engine-type="kv1"` setting or json/yaml export format. The json or yaml files look good but after import, the secret objects have been placed under the `data/` path rendering the import useless.

**Comment by jonasvinther** [comment]
Hi @kayahk 
That sounds strange. Are you sure that both the Vault secret engine is a kv1 and not kv2? That counts both the Vault instance where you do the export and the import.
