### ISSUE TITLE
Doesn't handle nested secrets with the same name.

### ISSUE THREAD

**Issue by tim-sendible** [jonasvinther/medusa#56]
Firstly, great product, helped me out with a Vault migration in record time. While I was doing the migration, I found an issue:

- We have a secret path of foo/bar
- Under foo/bar, there is a secret called 'moo'
- Also under foo/bar, this is a directory, also called 'moo' that contains further secrets.

eg:
```
foor/bar
    moo
    moo/wibble
```

Medusa skipped exporting the secret 'moo' and instead only exported the directory called 'moo'. No errors in logs. I suspect it just passed over the secret due to it having the same name as the directory in the same path.

This is exporting from Vault 1.7.1. The secret engine is kv2

**Comment by vvaltia** [comment]
I faced the same issue. I modified the code and built my own version of medusa. Seems to have solved this issue. It's my first time touching go code, so not sure how elegant the solution is. Since I don't have push rights to the repo what would be the best way to share my changes?

**Comment by tim-sendible** [comment]
The usual approach would be that you make a change on a fork of the project and then you create a Pull Request in this project to merge yours in. However, given I've not had a response from the maintainer on this issue, you may find that your PR does not get approved.

**Comment by vvaltia** [comment]
Thanks. Here are my changes.
https://github.com/jonasvinther/medusa/pull/59

**Comment by jonasvinther** [comment]
Hi @vvaltia and @tim-sendible 
Great to see that you could help each other out! I have created a new release v0.2.4 that contains the new changes.

**Comment by Joakim-Byg** [comment]
I saw the bug demonstrated in the presentation video by Henrik; just wanted to let you know that. Specifically, when he demonstrates:
"Da: Yaml Value" within the Vault UI (so it's imported), the secret is missing from the subsequent export yaml
