### ISSUE TITLE
build error after initial clone

### ISSUE THREAD

**Issue by kosmoit** [jonasvinther/medusa#57]
New to medusa.  cloned the repo, and performed a go build and received the following output.

`go build .
go: github.com/hashicorp/vault/api@v1.0.4 requires
        github.com/hashicorp/vault/sdk@v0.1.13 requires
        golang.org/x/text@v0.3.1-0.20181227161524-e6919f6577db: invalid pseudo-version: git fetch --unshallow -f origin:
        fatal: git fetch-pack: expected shallow list
`

any suggestions would be greatly appreciated.

**Comment by jonasvinther** [comment]
Hi @kosmoit 
It looks like your git version might be too old. Have a look at this: https://github.com/golang/go/issues/38373
Otherwise feel free to reopen the issue, and I will be happy to help you debug this.
