### ISSUE TITLE
Support for namespaces (Vault Enterprise)

### ISSUE THREAD

**Issue by cwien** [jonasvinther/medusa#60]
Vault Enterprise has the concept of "Namespaces" to isolate different environments.

The Vault API provides passing the namespace as an additional parameter, but medusa does not accept such a value on the command line yet. As we are using the Enterprise version of Vault we cannot use medusa until this option can be set. 

In the vaultclient.go there is already the stub to support namespaces, but the commands are not yet aware of this parameter.

I added those parameters and will create a PR that will add a "namespace flag" to the commands.

**Comment by cwien** [comment]
#61 is the PR for this issue.

**Comment by jonasvinther** [comment]
Again thank you for your contribution @cwien
