### ISSUE TITLE
medusa import: Access Entities support

### ISSUE THREAD

**Issue by sergey-plevako-badoo** [jonasvinther/medusa#72]
I am trying to import the Access Entity using medusa. I wonder if this is possible? I have tried importing the ACL Policies and it works fine. Consider I have the userpass Auth Method enabled with the Accessor "auth_userpass_966f2d29"

Let's say there is a "test" user created.  Exporting those user works fine

> ./medusa export -n sys identity/entity/name -m kv1 -f json -o output.json
It produces the file [output.json.zip](https://github.com/jonasvinther/medusa/files/7514697/output.json.zip)

My next step is to import that user back
> ./medusa import identity -m kv1 output.json  
Error while writing secret. json: unsupported type: importer.RawYaml

For us, it is important to back up not only the secrets but also the ACL Policies and Access Entities info as well.

**Comment by sergey-plevako-badoo** [comment]
[bob.smith.json.zip](https://github.com/jonasvinther/medusa/files/7520636/bob.smith.json.zip)

I am trying to use the following API  https://learn.hashicorp.com/tutorials/vault/identity

```
curl \
    --header "X-Vault-Token: 00000000-0000-0000-0000-000000000000" \
    --request POST \
    --insecure \
    --data @bob.smith.json \
    https://127.0.0.1:8201/v1/identity/entity
```

**Comment by jonasvinther** [comment]
Hi @sergey-plevako-badoo 
It looks like it's unable to parse the json during import for some reason. Can you try to export it as yaml and see if that changes anything? If you remove `-f json` from the export command you will get the output in yaml format. Let me know if that will fix it for you, then I will try to figure out where the error is.

**Comment by jonasvinther** [comment]
Only kv1 and kv2 secret engines are currently supported by Medusa.
