### ISSUE TITLE
Not able to export data of transit and totp

### ISSUE THREAD

**Issue by urkishan** [jonasvinther/medusa#73]
I am not able to export the data of transit and totp, here is the command I used when I started my vault :

`vault secrets enable totp transit`
`vault secrets disable secret`
`vault secrets enable kv -path=secret -version=1`

And when I run command to export the data it showing me error:

`./medusa export transit/ -m kv1 --address="http://0.0.0.0:8200" --token="s.token"  -o testing.yaml`

Response :
```
no keys found using path [transit//] on Vault instance [http://0.0.0.0:8200]
Error: no keys found using path [transit//] on Vault instance [http://0.0.0.0:8200]
Usage:
  medusa export [vault path] [flags]

Flags:
  -e, --encrypt              Encrypt the exported Vault data
  -m, --engine-type string   Specify the secret engine type [kv1|kv2] (default "kv2")
  -f, --format string        Specify the export format [yaml|json] (default "yaml")
  -h, --help                 help for export
  -o, --output string        Write to file instead of stdout
  -p, --public-key string    Location of the RSA public key

Global Flags:
  -a, --address string     Address of the Vault server
  -k, --insecure           Allow insecure server connections when using SSL
  -n, --namespace string   Namespace within the Vault server (Enterprise only)
  -t, --token string       Vault authentication token

no keys found using path [transit//] on Vault instance [http://0.0.0.0:8200]

```
I did try these too but same error :
 ```
 ./medusa export secrets/transit -m kv1 --address="http://0.0.0.0:8200" --token="s.token"  -o testing.yaml
 ./medusa export secrets/transit/secret_file -m kv1 --address="http://0.0.0.0:8200" --token="s.token"  -o testing.yaml
 ```
 
```
 / # vault version
Vault v1.3.0
```

Please let me know if there is anything I am doing wrong.

**Comment by jonasvinther** [comment]
Hi @urkishan 
Medusa only supports the kv1 and kv2 secret engines. We don't support for the TOTP secret engine at the moment.
It is not something that I plan to support at the moment, so I'm closing this issue.

**Comment by urkishan** [comment]
@jonasvinther is there any way to move TOTP data?

**Comment by nkhatwani-unicommerce** [comment]
@urkishan Were you able to find any workaround the same specifically for transit engine(export of encryption keys)
