### ISSUE TITLE
[Feature Request] Add search option

### ISSUE THREAD

**Issue by aabouzaid** [jonasvinther/medusa#76]
Hi, thanks for that great tool it's super handy :clap: 

Since the tool actually is able to export, I believe it would be easy to have a `search` option so I can find where exactly a `key` or a `value` is used given a certain path.

What I do at the moment is export everything in the path and search that using the text editor which is suboptimal.

Example:
```
medusa search secret/folder foo
```

It could also have the option to search in keys only or values only, but that's nice to have.

**Comment by dmpe** [comment]
There is a similar tool that could be of an interest to everyone: https://github.com/xbglowx/vault-kv-search
