### ISSUE TITLE
0.3.2 breaks kv1 export (Darwin release)

### ISSUE THREAD

**Issue by minorgod** [jonasvinther/medusa#78]
Not sure if this happens on other architectures, but something about 0.3.2 broke export with --engine-type="kv1". 
Version 0.3.1 works for me though.  Not sure if import is also affected as I'm only using medusa for export at the moment.

**Comment by jonasvinther** [comment]
Hi @minorgod
Can you post the error message you are getting? I don't have a Mac, so it's hard for me to debug this issue.

**Comment by minorgod** [comment]
> Hi @minorgod Can you post the error message you are getting? I don't have a Mac, so it's hard for me to debug this issue.

Thanks for the speedy reply!
There's no "error" message per se...it just can't find any keys to read...
`./medusa export mountname --format="json" --engine-type="kv1" `
```
no keys found using path [/path] on Vault instance [http://vault.mydomain.test:8200]
Error: no keys found using path [/path] on Vault instance [http://vault.mydomain.test:8200]
```
Fairly sure it's not an issue with needing any other flags or env vars since the previous version of medusa works fine. Seems like something in that [latest commit ](https://github.com/jonasvinther/medusa/commit/3357102152e6bf03b4c6e0e06e620118ab812ec4) has broken the path resoution. Maybe something adding or stripping off a slash somewhere it shouldn't? I'm not a golang programmer so it's hard for me to tell just by looking at the code.

**Comment by jonasvinther** [comment]
How does your mountname look? Does it contain special characters like / or something like that?

**Comment by mks-sky** [comment]
I can confirm having the same issue with 0.3.2 and 0.3.3 on WLS running Ubuntu 20.04 LTS - we've reverted to 0.3.1.  The error message with %s = /path is the same regardless of whether `medusa export secrets` or `medusa export secrets/` or `medusa export my/secrets` - looks like `finalPath` variable is not being built correctly.

**Comment by jonasvinther** [comment]
I have made a new release [v0.3.5](https://github.com/jonasvinther/medusa/releases/tag/v0.3.5). Thank you @landrew57 for solving this issue.
