### ISSUE TITLE
Import from stdin

### ISSUE THREAD

**Issue by jozefs** [jonasvinther/medusa#80]
Thanks for the great tool. I already have [SOPS](https://github.com/mozilla/sops)+[age](https://github.com/FiloSottile/age) set up to manage encryption and decryption of files in my projects, so I only need Medusa for the import/export functionality. It does not seem obvious to me from the documentation and command line help if it is possible to import from stdin. The scenario is using SOPS to decrypt to stdout and then using Medusa to import the decrypted backup from stdin without having to write the decrypted backup to an intermediate file. Is this possible with the current version of Medusa?

**Comment by jonasvinther** [comment]
Hi @jozefs 
This feature has been added in version 0.3.6: https://github.com/jonasvinther/medusa/releases/tag/v0.3.6

**Comment by jozefs** [comment]
Thank you so much 🙏
