### ISSUE TITLE
Needs M1 (arm64) Build for MacOS 

### ISSUE THREAD

**Issue by BojanZelic** [jonasvinther/medusa#83]
Hi, 

It would be nice to have a pre-compiled arm64 Darwin build

**Comment by jonasvinther** [comment]
Hi @BojanZelic 
I have added a version 0.3.4 that has a compiled arm64 Darwin build. Can you verify that it is working? I don't have a Mac :)
https://github.com/jonasvinther/medusa/releases/tag/v0.3.4

**Comment by BojanZelic** [comment]
Awesome, seems to work great! Thank you!
