### ISSUE TITLE
config.yaml Issue

### ISSUE THREAD

**Issue by BK-STAR77** [jonasvinther/medusa#87]
Medusa does not take my configuration listed on config.yaml. So I have to put in variable to make it work

**Comment by jonasvinther** [comment]
Hi @BK-STAR77 
Thank you for reaching out. Can you elaborate a bit on what you mean  by this?

**Comment by BK-STAR77** [comment]
I create a config.yaml to my homefolder  ~/.medusa/config.yaml but it looks like read my conf however it works fine with environment.

**Comment by jonasvinther** [comment]
Medusa has no issues reading my `~/.medusa/config.yaml` file.
The config file could look something like this.
```bash
VAULT_ADDR: https://localhost:8201
VAULT_SKIP_VERIFY: true
VAULT_TOKEN: my-secret-token
```
I will close this issue since I cannot replicate the error.
